version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - wira-network
    ports:
      - "3001:80"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=aqash18
      - DB_NAME=wira_dashboard
      - SEED_NUM_USERS=5000
    command: sh -c "./wait-for-postgres.sh db && ./main"
    networks:
      - wira-network
    ports:
      - "8081:8081"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aqash18
      - POSTGRES_DB=wira_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01_init.sql
    networks:
      - wira-network

  seeder:
    build:
      context: .
      dockerfile: database/seed/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=aqash18
      - DB_NAME=wira_dashboard
      - SEED_NUM_USERS=5000
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db", "./seed"]
    networks:
      - wira-network

volumes:
  postgres_data:

networks:
  wira-network:
    driver: bridge
