version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: 173.212.239.58:5000/frontend:latest
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - wira-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: 173.212.239.58:5000/backend:latest
    ports:
      - "8081:8080"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - wira-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aqash18
      - POSTGRES_DB=wira_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01_init.sql
    ports:
      - "5435:5432"
    networks:
      - wira-network

  seeder:
    build:
      context: ./database/seed
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=aqash18
      - DB_NAME=wira_dashboard
      - SEED_NUM_USERS=100
    depends_on:
      - db
    networks:
      - wira-network

volumes:
  postgres_data:

networks:
  wira-network:
    driver: bridge
